# Generated by Django 5.2.7 on 2025-10-26 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0001_initial'),
        ('people', '0003_alter_ownership_flat_alter_ownership_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('UBER_DRIVER', 'Uber driver'), ('RENTAL_COMPANY', 'Rental company')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., P-01', max_length=10, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('is_reserved', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('flat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_spot', to='flats.flat')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('MICROBUS', 'Microbus'), ('TRUCK', 'Truck'), ('OTHER', 'Other')], default='CAR', max_length=20)),
                ('make', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('tag_no', models.CharField(blank=True, help_text='RFID / Sticker no (optional)', max_length=50)),
                ('owner_type', models.CharField(choices=[('OWNER', 'Owner'), ('LESSEE', 'Lessee'), ('UBER_DRIVER', 'Uber driver'), ('RENTAL_COMPANY', 'Rental company')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='parking.externalowner')),
                ('flat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='flats.flat')),
                ('lessee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='people.lessee')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='people.owner')),
            ],
            options={
                'ordering': ['plate_no'],
            },
        ),
        migrations.CreateModel(
            name='ParkingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='parking.parkingspot')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='parking.vehicle')),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('vehicle__isnull', False)), fields=('vehicle',), name='one_active_assignment_per_vehicle'), models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('spot',), name='one_active_assignment_per_spot')],
            },
        ),
    ]
