# Generated by Django 5.2.7 on 2025-10-25 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=8, unique=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('flat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spot', to='flats.flat')),
            ],
            options={
                'ordering': ['flat__floor', 'flat__unit'],
            },
        ),
        migrations.DeleteModel(
            name='Placeholder',
        ),
        migrations.AddField(
            model_name='parkingassignment',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='parking.parkingspot'),
        ),
        migrations.AddConstraint(
            model_name='parkingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('spot',), name='one_active_parking_per_spot'),
        ),
    ]
