# Generated by Django 5.2.7 on 2025-10-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingassignment',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='code',
            field=models.CharField(help_text='e.g., E-10', max_length=10, unique=True),
        ),
    ]
