# Generated by Django 5.2.7 on 2025-10-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField()),
                ('unit', models.CharField(max_length=1)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('status_hint', models.CharField(choices=[('vacant', 'Vacant'), ('owner', 'Owner-occupied'), ('rented', 'Rented')], default='vacant', max_length=10)),
            ],
            options={
                'ordering': ['floor', 'unit'],
                'unique_together': {('floor', 'unit')},
            },
        ),
    ]
