# Generated by Django 5.2.7 on 2025-10-25 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
        ('people', '0002_lessee_owner_ownership_tenancy_delete_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='flats.flat'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='people.owner'),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='flats.flat'),
        ),
        migrations.AlterField(
            model_name='tenancy',
            name='lessee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='people.lessee'),
        ),
        migrations.AddIndex(
            model_name='ownership',
            index=models.Index(fields=['flat', 'end_date'], name='own_flat_end_idx'),
        ),
        migrations.AddIndex(
            model_name='ownership',
            index=models.Index(fields=['flat', 'start_date'], name='own_flat_start_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['flat', 'end_date'], name='ten_flat_end_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['flat', 'start_date'], name='ten_flat_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('flat',), name='one_active_ownership_per_flat'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('flat',), name='one_active_tenancy_per_flat'),
        ),
    ]
